module.exports = [
  {
    date: "03/02/2021",
    name: "4K Plasma TV",
    amount: -525,
    from: "Best Buy Inc.",
    category: "Shopping",
  },
  {
    date: "03/05/2021",
    name: "Dinner",
    amount: -100,
    from: "Rosa Mexicana",
    category: "Dining",
  },
  {
    date: "03/08/2021",
    name: "Dog Food",
    amount: -50,
    from: "Petco",
    category: "Pet",
  },
  {
    date: "03/09/2021",
    name: "Salary",
    amount: 1500,
    from: "Local 3 IBEW",
    category: "Income",
  },
  {
    date: "03/09/2021",
    name: "Dividends",
    amount: 150,
    from: "Charles Schwab",
    category: "Investments",
  },
  {
    date: "03/10/2021",
    name: "Beyonce",
    amount: -600,
    from: "Ticketmaster",
    category: "Entertainment",
  },
  {
    date: "03/12/2021",
    name: "Electric",
    amount: -100,
    from: "Con Edison",
    category: "Utilities",
  },
];
