module.exports = [
  {
    date: "06/10/2022",
    name: "4K Plasma TV",
    amount: -525,
    from: "Best Buy Inc.",
    category: "Shopping",
  },
  {
    date: "06/11/2022",
    name: "Dinner",
    amount: -100,
    from: "Rosa Mexicana",
    category: "Dining & Drinks",
  },
  {
    date: "06/12/2022",
    name: "Dog Food",
    amount: -50,
    from: "Petco",
    category: "Pet",
  },
  {
    date: "06/14/2022",
    name: "Pay Day",
    amount: 1500,
    from: "Local 3 IBEW",
    category: "Wages & Income",
  },
  {
    date: "06/15/2022",
    name: "Dividends",
    amount: 150,
    from: "Charles Schwab",
    category: "Investments",
  },
  {
    date: "06/17/2022",
    name: "Beyonce Concert at MSG",
    amount: -500,
    from: "Ticketmaster",
    category: "Entertainment",
  },
  {
    date: "06/18/2022",
    name: "Electric",
    amount: -100,
    from: "Con Edison",
    category: "Utilities",
  },
  {
    date: "06/19/2022",
    name: "Drinks",
    amount: -25,
    from: "Sean Og's Pub",
    category: "Dining & Drinks",
  },
  {
    date: "06/19/2022",
    name: "Internet",
    amount: -45,
    from: "Verizon Fios",
    category: "Utilities",
  },
  {
    date: "06/28/2022",
    name: "Pay Day",
    amount: 1500,
    from: "Local 3 IBEW",
    category: "Wages & Income",
  },
  {
    date: "07/01/2022",
    name: "Rent",
    amount: -1550,
    from: "Rent LLC",
    category: "Rent & Mortgage",
  },
  {
    date: "07/02/2022",
    name: "Gym",
    amount: -200,
    from: "Equinox",
    category: "Dues & Memberships",
  },
  {
    date: "07/03/2022",
    name: "Dentist",
    amount: -30,
    from: "Corona Dental",
    category: "Health & Wellness",
  },
];
